import { routeHasParams } from "./scan";

const HEADER = "// AUTO-GENERATED by react-router-next typegen — do not edit.";

/**
 * Source emitted into the **runtime** virtual module for a given route key.
 * Plain JavaScript — type info lives in the ambient `.d.ts` shim emitted by
 * `renderDtsShim`. Virtual modules aren't transformed as TypeScript by Vite,
 * so the runtime form must not contain type-only syntax.
 */
export function renderRuntimeModule(routeKey: string): string {
  if (!routeHasParams(routeKey)) {
    return `${HEADER}
import { generateUrl } from "@evolonix/react-router-next";

const PATH = ${JSON.stringify(routeKey)};

export function generate() {
  return generateUrl(PATH, {});
}
`;
  }

  return `${HEADER}
import {
  generateUrl,
  useRouteParams as useRouteParamsBase,
} from "@evolonix/react-router-next";

const PATH = ${JSON.stringify(routeKey)};

export function useRouteParams() {
  return useRouteParamsBase(PATH);
}

export function generate(params) {
  return generateUrl(PATH, params);
}
`;
}

/**
 * Body of a `declare module 'virtual:react-router-next/<route-key>' { ... }`
 * block. Same shape as the runtime module, but with type-only declarations so
 * `tsc` and editors resolve consumer imports without spinning up Vite.
 */
function renderDeclareBody(routeKey: string): string {
  if (!routeHasParams(routeKey)) {
    return `  import type { RouteParams as RouteParamsBase } from "@evolonix/react-router-next";
  const PATH: ${JSON.stringify(routeKey)};
  export type RouteParams = RouteParamsBase<typeof PATH>;
  export function generate(): string;
`;
  }
  return `  import type { RouteParams as RouteParamsBase } from "@evolonix/react-router-next";
  const PATH: ${JSON.stringify(routeKey)};
  export type RouteParams = RouteParamsBase<typeof PATH>;
  export type RouteProps = { params: RouteParams };
  export function useRouteParams(): RouteParams;
  export function generate(params: RouteParams): string;
`;
}

export function virtualIdFor(routeKey: string): string {
  return `virtual:react-router-next/${routeKey === "" ? "_root" : routeKey}`;
}

/**
 * Emit a single ambient `.d.ts` shim covering every discovered route. Import
 * specifiers that consumers write (e.g.
 * `virtual:react-router-next/posts/[postId]`) resolve to a `declare module`
 * block in this file at type-check time.
 */
export function renderDtsShim(routeKeys: readonly string[]): string {
  const blocks = routeKeys.map((key) => {
    const id = virtualIdFor(key);
    return `declare module ${JSON.stringify(id)} {
${renderDeclareBody(key)}}
`;
  });
  return `${HEADER}
// Ambient declarations for react-router-next virtual route modules.
// Generated by \`react-router-next typegen\` and the routeTypegen Vite plugin.

declare module "virtual:react-router-next/app-tree" {
  import type { ComponentType } from "react";
  import type { LoaderFunction } from "react-router";

  export type RouteModule = {
    default?: ComponentType<{
      params?: Record<string, string | string[] | undefined>;
    }>;
    loader?: LoaderFunction;
  };

  export const modules: Record<string, RouteModule>;
  export const appDir: string;
}

${blocks.join("\n")}`;
}
