import { readdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const PAGE_RE = /^(page|layout)\.(tsx|jsx|ts|js)$/;
const TYPES_RE = /^route\.types\.ts$/;

function toPosix(p) {
  return p.split("\\").join("/");
}

function findFiles(appDir) {
  const entries = readdirSync(appDir, {
    recursive: true,
    withFileTypes: true,
  });
  const sourceDirs = new Set();
  const stale = [];
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    const dir = entry.parentPath ?? entry.path;
    const full = join(dir, entry.name);
    if (PAGE_RE.test(entry.name)) {
      sourceDirs.add(dir);
    } else if (TYPES_RE.test(entry.name)) {
      stale.push(full);
    }
  }
  return { sourceDirs: [...sourceDirs], stale };
}

function routeKeyFor(appDir, fileDir) {
  const rel = toPosix(relative(appDir, fileDir));
  return rel === "" ? "" : rel;
}

function libImportFor(fileDir, libFile) {
  const rel = toPosix(relative(fileDir, libFile));
  const noExt = rel.replace(/\.ts$/, "");
  return noExt.startsWith(".") ? noExt : `./${noExt}`;
}

function hasParams(routeKey) {
  return routeKey.includes("[");
}

function renderTemplate({ libImport, routeKey }) {
  if (!hasParams(routeKey)) {
    return `// AUTO-GENERATED — do not edit. Regenerated by vite-plugin-typegen.
import {
  generateUrl,
  type RouteParams as RouteParamsBase,
} from "${libImport}";

const PATH = "${routeKey}";

export type RouteParams = RouteParamsBase<typeof PATH>;

export function generate(): string {
  return generateUrl(PATH, {} as RouteParams);
}
`;
  }

  return `// AUTO-GENERATED — do not edit. Regenerated by vite-plugin-typegen.
import {
  generateUrl,
  useRouteParams as useRouteParamsBase,
  type RouteParams as RouteParamsBase,
} from "${libImport}";

const PATH = "${routeKey}";

export type RouteParams = RouteParamsBase<typeof PATH>;
export type RouteProps = { params: RouteParams };

export function useRouteParams(): RouteParams {
  return useRouteParamsBase(PATH);
}

export function generate(params: RouteParams): string {
  return generateUrl(PATH, params);
}
`;
}

function writeIfChanged(path, contents) {
  try {
    const existing = readFileSync(path, "utf8");
    if (existing === contents) return false;
  } catch {
    // file missing — fall through to write
  }
  writeFileSync(path, contents);
  return true;
}

export function generateRouteTypes({ appDir, libFile, clean = false } = {}) {
  const root = resolve(appDir ?? "src/app");
  const lib = resolve(libFile ?? "src/lib/use-route-params.ts");
  const { sourceDirs, stale } = findFiles(root);

  if (clean) {
    let removed = 0;
    for (const dir of sourceDirs) {
      stale.push(join(dir, "route.types.ts"));
    }
    const seen = new Set();
    for (const s of stale) {
      const key = toPosix(s);
      if (seen.has(key)) continue;
      seen.add(key);
      try {
        unlinkSync(s);
        removed++;
      } catch {
        // already gone
      }
    }
    return { written: 0, removed, total: 0 };
  }

  const wanted = new Set();
  let written = 0;
  for (const dir of sourceDirs) {
    const out = join(dir, "route.types.ts");
    wanted.add(toPosix(out));
    const contents = renderTemplate({
      libImport: libImportFor(dir, lib),
      routeKey: routeKeyFor(root, dir),
    });
    if (writeIfChanged(out, contents)) written++;
  }

  let removed = 0;
  for (const s of stale) {
    if (!wanted.has(toPosix(s))) {
      unlinkSync(s);
      removed++;
    }
  }

  return { written, removed, total: wanted.size };
}

const isCli =
  import.meta.url === pathToFileURL(process.argv[1] ?? "").href ||
  process.argv[1]?.endsWith("typegen.mjs");

if (isCli) {
  const here = dirname(fileURLToPath(import.meta.url));
  const projectRoot = resolve(here, "..", "..");
  const clean = process.argv
    .slice(2)
    .some((a) => a === "--clean" || a === "-c");
  const result = generateRouteTypes({
    appDir: join(projectRoot, "src", "app"),
    libFile: join(projectRoot, "src", "lib", "use-route-params.ts"),
    clean,
  });
  if (clean) {
    console.log(`[typegen] cleaned ${result.removed} type file(s)`);
  } else {
    console.log(
      `[typegen] ${result.total} type files (${result.written} written, ${result.removed} removed)`,
    );
  }
}
