import { readdirSync, readFileSync, writeFileSync, unlinkSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const PAGE_RE = /^(page|layout)\.(tsx|jsx|ts|js)$/;
const TYPES_RE = /^(page|layout)\.types\.ts$/;

function toPosix(p) {
  return p.split("\\").join("/");
}

function findFiles(appDir) {
  const entries = readdirSync(appDir, {
    recursive: true,
    withFileTypes: true,
  });
  const sources = [];
  const stale = [];
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    const dir = entry.parentPath ?? entry.path;
    const full = join(dir, entry.name);
    if (PAGE_RE.test(entry.name)) {
      const kind = entry.name.startsWith("page") ? "page" : "layout";
      sources.push({ dir, full, kind });
    } else if (TYPES_RE.test(entry.name)) {
      stale.push(full);
    }
  }
  return { sources, stale };
}

function routeKeyFor(appDir, fileDir) {
  const rel = toPosix(relative(appDir, fileDir));
  return rel === "" ? "" : rel;
}

function libImportFor(fileDir, libFile) {
  const rel = toPosix(relative(fileDir, libFile));
  const noExt = rel.replace(/\.ts$/, "");
  return noExt.startsWith(".") ? noExt : `./${noExt}`;
}

function renderTemplate({ libImport, routeKey }) {
  return `// AUTO-GENERATED — do not edit. Regenerated by vite-plugin-typegen.
import {
  generateUrl,
  useRouteParams as useRouteParamsBase,
  type RouteParams as RouteParamsBase,
} from "${libImport}";

export type RouteParams = RouteParamsBase<"${routeKey}">;
export type PageProps = { params: RouteParams };

export function useRouteParams(): RouteParams {
  return useRouteParamsBase("${routeKey}");
}

export function generate(params: RouteParams): string {
  return generateUrl("${routeKey}", params);
}
`;
}

function writeIfChanged(path, contents) {
  try {
    const existing = readFileSync(path, "utf8");
    if (existing === contents) return false;
  } catch {
    // file missing — fall through to write
  }
  writeFileSync(path, contents);
  return true;
}

export function generateRouteTypes({ appDir, libFile } = {}) {
  const root = resolve(appDir ?? "src/app");
  const lib = resolve(libFile ?? "src/lib/useRouteParams.ts");
  const { sources, stale } = findFiles(root);

  const wanted = new Set();
  let written = 0;
  for (const { dir, kind } of sources) {
    const out = join(dir, `${kind}.types.ts`);
    wanted.add(toPosix(out));
    const contents = renderTemplate({
      libImport: libImportFor(dir, lib),
      routeKey: routeKeyFor(root, dir),
    });
    if (writeIfChanged(out, contents)) written++;
  }

  let removed = 0;
  for (const s of stale) {
    if (!wanted.has(toPosix(s))) {
      unlinkSync(s);
      removed++;
    }
  }

  return { written, removed, total: wanted.size };
}

const isCli =
  import.meta.url === pathToFileURL(process.argv[1] ?? "").href ||
  process.argv[1]?.endsWith("typegen.mjs");

if (isCli) {
  const here = dirname(fileURLToPath(import.meta.url));
  const projectRoot = resolve(here, "..", "..");
  const result = generateRouteTypes({
    appDir: join(projectRoot, "src", "app"),
    libFile: join(projectRoot, "src", "lib", "useRouteParams.ts"),
  });
  console.log(
    `[typegen] ${result.total} type files (${result.written} written, ${result.removed} removed)`,
  );
}
